### ISSUE TITLE
[Chore] 개발 초기 설정을 위한 build.gradle/ .gitignore  파일 설정

### ISSUE THREAD

**Issue by fredlee613** [MayToOne/manytoone-server-java#1]
## Decription
작업 목표를 작성해주세요.
***
## Todo List
- [x] 민감 정보가 포함된 application.yml을 .gitignore 파일에 추가
- [x] querydsl 라이브러리 사용을 위한 build.gradle 파일 설정
- [x] 로깅 기능 개선을 위한 gavlyukovskiy:p6spy-spring-boot-starter:1.9.0' 의존성 주입
***
