### ISSUE TITLE
[Feat] 도메인 기본 CRUD 기능 추가 및 테스트 코드 추가

### ISSUE THREAD

**Issue by fredlee613** [MayToOne/manytoone-server-java#4]
## Decription
작업 목표를 작성해주세요.
***
## Todo List
- [x] 회원 도메인 클래스 및 레포지토리 클래스 추가
- [x] 마니또 도메인 클래스 및 레포지토리 클래스 추가
- [x] 회원관리 도메인 클래스 및 레포지토리 클래스 추가
- [x] 마니또 회원 관리 도메인 클래스 및 레포지토리 클래스 추가
- [x] 생성날짜/ 마지막 수정날짜/ 마지막으로 수정한 사용자 관련 BaseEntity 추가 -> @EnableJpaAuditing 어노테이션 추가
- [x] 각 클래스별 테스트 코드 추가
