### ISSUE TITLE
[Bug] 엔티티 Cascading on delete 작동 오류

### ISSUE THREAD

**Issue by fredlee613** [MayToOne/manytoone-server-java#7]
## Decription
DB 상에는 Cascading on delete와 update를 설정하여 자동으로 삭제가 되지만 JPA 상에서는 삭제 쿼리가 나가지 않는다.
***
## Todo List
- [ ] JPA PersistContext 학습
- [ ] 연관관계 학습
- [ ] Entitiy class 수정 및 Cascade.remove, orphanRemoval = true 적용 
- [ ] 테스트 코드에 삭제 내역 확인 가능한 코드 추가
***
