### ISSUE TITLE
[Chore]  SpringDocs, Swagger 적용

### ISSUE THREAD

**Issue by fredlee613** [MayToOne/manytoone-server-java#8]
## Decription
API 스펙을 명시해주기 위하여 SpringDocs 또는 Swagger 적용
***
## Todo List
- [ ] Swagger 학습
- [ ] Spring Docs 학습
- [ ] Swagger의 경우 Controller 클래스에 적용
- [ ] Spring Docs의 경우 테스트 코드 작성
***
